---
http_interactions:
- request:
    method: get
    uri: http://api.themoviedb.org/3/configuration?api_key=c29379565234e20d7cbf4f2e835c3e41&language=en
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Origin:
      - "*"
      Cache-Control:
      - public, max-age=36000
      Content-Type:
      - application/json;charset=utf-8
      Date:
      - Tue, 23 Jun 2015 14:07:10 GMT
      Etag:
      - '"acd3a349fca1f788ac931639278ad061"'
      Server:
      - openresty
      Status:
      - 200 OK
      Vary:
      - Accept-Encoding
      X-Ratelimit-Limit:
      - '40'
      X-Ratelimit-Remaining:
      - '39'
      X-Ratelimit-Reset:
      - '1435068433'
      Content-Length:
      - '1073'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"images":{"base_url":"http://image.tmdb.org/t/p/","secure_base_url":"https://image.tmdb.org/t/p/","backdrop_sizes":["w300","w780","w1280","original"],"logo_sizes":["w45","w92","w154","w185","w300","w500","original"],"poster_sizes":["w92","w154","w185","w342","w500","w780","original"],"profile_sizes":["w45","w185","h632","original"],"still_sizes":["w92","w185","w300","original"]},"change_keys":["adult","air_date","also_known_as","alternative_titles","biography","birthday","budget","cast","certifications","character_names","created_by","crew","deathday","episode","episode_number","episode_run_time","freebase_id","freebase_mid","general","genres","guest_stars","homepage","images","imdb_id","languages","name","network","origin_country","original_name","original_title","overview","parts","place_of_birth","plot_keywords","production_code","production_companies","production_countries","releases","revenue","runtime","season","season_number","season_regular","spoken_languages","status","tagline","title","translations","tvdb_id","tvrage_id","type","video","videos"]}'
    http_version: 
  recorded_at: Tue, 23 Jun 2015 14:07:10 GMT
recorded_with: VCR 2.9.3
