name: Ruby specs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Tests for ${{ matrix.ruby.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: "Ruby 3.2.x", value: 3.2.0 }
          - { name: "Ruby 3.1.x", value: 3.1.3 }
          - { name: "Ruby 3.0.x", value: 3.0.5 }
          - { name: "Ruby 2.7.x", value: 2.7.7 }
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
